name: Terraform Deployment

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the repo
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: Azure/login@v2
        with: 
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      

      # Step 2: Setup Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.7.5  # change to your version

      # Step 3: Terraform Init (with backend config if needed)
      - name: Terraform init azurerm backend
        uses: ahmedig/terraform-azurerm-backend@v4
        with:
            azure_credentials: ${{ secrets.AZURE_CREDENTIALS }}
            resource_group_name: backendrg
            container_name: backendcontainer
            storage_account_name: backendstrge

      # Step 4: Terraform Plan
      - name: Terraform Plan
        run: terraform plan 

      # Step 5: Terraform Apply
      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan
